name: Check PR

on: [pull_request]

jobs:
  danger:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.5]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run danger checks
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: npx danger ci
