name: Test

on: [pull_request]

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.20.1]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test
